version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: 
      - ./db/db.env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d image-ranking-db -U zeinovich"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - image-ranking

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    env_file: 
      - ./db/pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - 5050:5050
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - image-ranking

  backend:
    container_name: backend
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    env_file:
      - backend/backend.env
    depends_on:
      - postgres
    links:
      - postgres
    networks:
      - image-ranking
    ports:
      - 8888:8888
    
  frontend:
    container_name: frontend
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    depends_on:
      - backend
    links:
      - backend
    networks:
      - image-ranking
    ports:
      - 8501:8501

volumes:
  postgres_db:
    external: true
  pgadmin_data:
    external: true

networks:
  image-ranking:
    external: true
