version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: 
      - db.env
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d image-ranking-db -U zeinovich"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    networks:
      - image-ranking

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    env_file: 
      - pgadmin.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    networks:
      - image-ranking

  backend:
    container_name: backend
    build: src/backend
    command: python src/db_init.py # copy init_file to backend
    env_file:
      - db.env  
    networks:
      - image-ranking
    ports:
      - "8888:8888"
    
  frontend:
    container_name: frontend
    build: src/frontend
    networks:
      - image-ranking
    ports:
      - "80:8501"

volumes:
  postgres_db:
  pgadmin_data:

networks:
  image-ranking:
