name: Python application

on: [push]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install flake8
        python -m pip install pytest
    - name: Analysing the code with flake8
      run: |
        flake8 --max-line-length=88 --ignore=F401 .
    - name: Testing the code
      run: |
        cd backend
        python -m pytest tests